### ISSUE TITLE
Channel Definition

### ISSUE THREAD

**Issue by stewartab** [AkshayMohan/pawn-discord-cmd#2]
Hi. How can I define the channel where the command will work??

**Comment by AkshayMohan** [comment]
DCMD already provides channel identifier along with the parameters. You can make use of `DCC_FindChannelById` or other functions to store the channel ID in your script and then compare it with the command.

Here's an example:
```pawn
#define MY_CHANNEL_ID "1234135413123";
static g_myChannel;

public OnFilterScriptInit() {
    g_myChannel = DCC_FindChannelById(MY_CHANNEL_ID);
}

DCMD:my_command(user, channel, params[]) {

    if(channel != g_myChannel) {
        DCC_SendChannelMessage(channel, "This only works on #my_channel");
    } else {
        DCC_SendChannelMessage(channel, "Hello World from #my_channel!");
    }
    return 1;
}
```

PS: Sorry for the late reply. Better late than never.
